package com.example.finalproduct;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class AddingMatrices extends AppCompatActivity {
    private EditText a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16;
    private EditText e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16;
    private TextView w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_adding_matrices);
        Button adding = findViewById(R.id.AddButton);
        Button subtraction = findViewById(R.id.subButton);
        a1=findViewById(R.id.d1);
        a2=findViewById(R.id.d2);
        a3=findViewById(R.id.d3);
        a4=findViewById(R.id.d4);
        a5=findViewById(R.id.d5);
        a6=findViewById(R.id.d6);
        a7=findViewById(R.id.d7);
        a8=findViewById(R.id.d8);
        a9=findViewById(R.id.d9);
        a10=findViewById(R.id.d10);
        a11=findViewById(R.id.d11);
        a12=findViewById(R.id.d12);
        a13=findViewById(R.id.d13);
        a14=findViewById(R.id.d14);
        a15=findViewById(R.id.d15);
        a16=findViewById(R.id.d16);
        e1=findViewById(R.id.b1);
        e2=findViewById(R.id.b2);
        e3=findViewById(R.id.b3);
        e4=findViewById(R.id.b4);
        e5=findViewById(R.id.b5);
        e6=findViewById(R.id.b6);
        e7=findViewById(R.id.b7);
        e8=findViewById(R.id.b8);
        e9=findViewById(R.id.b9);
        e10=findViewById(R.id.b10);
        e11=findViewById(R.id.b11);
        e12=findViewById(R.id.b12);
        e13=findViewById(R.id.b13);
        e14=findViewById(R.id.b14);
        e15=findViewById(R.id.b15);
        e16=findViewById(R.id.b16);
        w1=findViewById(R.id.r1);
        w2=findViewById(R.id.r2);
        w3=findViewById(R.id.r3);
        w4=findViewById(R.id.r4);
        w5=findViewById(R.id.r5);
        w6=findViewById(R.id.r6);
        w7=findViewById(R.id.r7);
        w8=findViewById(R.id.r8);
        w9=findViewById(R.id.r9);
        w10=findViewById(R.id.r10);
        w11=findViewById(R.id.r11);
        w12=findViewById(R.id.r12);
        w13=findViewById(R.id.r13);
        w14=findViewById(R.id.r14);
        w15=findViewById(R.id.r15);
        w16=findViewById(R.id.r16);

        adding.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(AddingMatrices.this, "It works!", Toast.LENGTH_SHORT).show();
                String s1=a1.getText().toString();
                String s2=a2.getText().toString();
                String s3=a3.getText().toString();
                String s4=a4.getText().toString();
                String s5=a5.getText().toString();
                String s6=a6.getText().toString();
                String s7=a7.getText().toString();
                String s8=a8.getText().toString();
                String s9=a9.getText().toString();
                String s10=a10.getText().toString();
                String s11=a11.getText().toString();
                String s12=a12.getText().toString();
                String s13=a13.getText().toString();
                String s14=a14.getText().toString();
                String s15=a15.getText().toString();
                String s16=a16.getText().toString();

                String p1=e1.getText().toString();
                String p2=e2.getText().toString();
                String p3=e3.getText().toString();
                String p4=e4.getText().toString();
                String p5=e5.getText().toString();
                String p6=e6.getText().toString();
                String p7=e7.getText().toString();
                String p8=e8.getText().toString();
                String p9=e9.getText().toString();
                String p10=e10.getText().toString();
                String p11=e11.getText().toString();
                String p12=e12.getText().toString();
                String p13=e13.getText().toString();
                String p14=e14.getText().toString();
                String p15=e15.getText().toString();
                String p16=e16.getText().toString();

                int i1=Integer.parseInt(s1);
                int i2 = Integer.parseInt(s2);
                int i3=Integer.parseInt(s3);
                int i4=Integer.parseInt(s4);
                int i5=Integer.parseInt(s5);
                int i6=Integer.parseInt(s6);
                int i7=Integer.parseInt(s7);
                int i8=Integer.parseInt(s8);
                int i9=Integer.parseInt(s9);
                int i10=Integer.parseInt(s10);
                int i11=Integer.parseInt(s11);
                int i12=Integer.parseInt(s12);
                int i13=Integer.parseInt(s13);
                int i14=Integer.parseInt(s14);
                int i15=Integer.parseInt(s15);
                int i16=Integer.parseInt(s16);

                int o1=Integer.parseInt(p1);
                int o2=Integer.parseInt(p2);
                int o3=Integer.parseInt(p3);
                int o4=Integer.parseInt(p4);
                int o5=Integer.parseInt(p5);
                int o6=Integer.parseInt(p6);
                int o7=Integer.parseInt(p7);
                int o8=Integer.parseInt(p8);
                int o9=Integer.parseInt(p9);
                int o10=Integer.parseInt(p10);
                int o11=Integer.parseInt(p11);
                int o12=Integer.parseInt(p12);
                int o13=Integer.parseInt(p13);
                int o14=Integer.parseInt(p14);
                int o15=Integer.parseInt(p15);
                int o16=Integer.parseInt(p16);

                int f1=i1+o1;
                int f2=i2+o2;
                int f3=i3+o3;
                int f4=i4+o4;
                int f5=i5+o5;
                int f6=i6+o6;
                int f7=i7+o7;
                int f8=i8+o8;
                int f9=i9+o9;
                int f10=i10+o10;
                int f11=i11+o11;
                int f12=i12+o12;
                int f13=i13+o13;
                int f14=i14+o14;
                int f15=i15+o15;
                int f16=i16+o16;

                String g1=Integer.toString(f1);
                String g2=Integer.toString(f2);
                String g3=Integer.toString(f3);
                String g4=Integer.toString(f4);
                String g5=Integer.toString(f5);
                String g6=Integer.toString(f6);
                String g7=Integer.toString(f7);
                String g8=Integer.toString(f8);
                String g9=Integer.toString(f9);
                String g10=Integer.toString(f10);
                String g11=Integer.toString(f11);
                String g12=Integer.toString(f12);
                String g13=Integer.toString(f13);
                String g14=Integer.toString(f14);
                String g15=Integer.toString(f15);
                String g16=Integer.toString(f16);

                w1.setText(g1);
                w2.setText(g2);
                w3.setText(g3);
                w4.setText(g4);
                w5.setText(g5);
                w6.setText(g6);
                w7.setText(g7);
                w8.setText(g8);
                w9.setText(g9);
                w10.setText(g10);
                w11.setText(g11);
                w12.setText(g12);
                w13.setText(g13);
                w14.setText(g14);
                w15.setText(g15);
                w16.setText(g16);
            }
        });
        subtraction.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String s1=a1.getText().toString();
                String s2=a2.getText().toString();
                String s3=a3.getText().toString();
                String s4=a4.getText().toString();
                String s5=a5.getText().toString();
                String s6=a6.getText().toString();
                String s7=a7.getText().toString();
                String s8=a8.getText().toString();
                String s9=a9.getText().toString();
                String s10=a10.getText().toString();
                String s11=a11.getText().toString();
                String s12=a12.getText().toString();
                String s13=a13.getText().toString();
                String s14=a14.getText().toString();
                String s15=a15.getText().toString();
                String s16=a16.getText().toString();

                String p1=e1.getText().toString();
                String p2=e2.getText().toString();
                String p3=e3.getText().toString();
                String p4=e4.getText().toString();
                String p5=e5.getText().toString();
                String p6=e6.getText().toString();
                String p7=e7.getText().toString();
                String p8=e8.getText().toString();
                String p9=e9.getText().toString();
                String p10=e10.getText().toString();
                String p11=e11.getText().toString();
                String p12=e12.getText().toString();
                String p13=e13.getText().toString();
                String p14=e14.getText().toString();
                String p15=e15.getText().toString();
                String p16=e16.getText().toString();

                int i1=Integer.parseInt(s1);
                int i2 = Integer.parseInt(s2);
                int i3=Integer.parseInt(s3);
                int i4=Integer.parseInt(s4);
                int i5=Integer.parseInt(s5);
                int i6=Integer.parseInt(s6);
                int i7=Integer.parseInt(s7);
                int i8=Integer.parseInt(s8);
                int i9=Integer.parseInt(s9);
                int i10=Integer.parseInt(s10);
                int i11=Integer.parseInt(s11);
                int i12=Integer.parseInt(s12);
                int i13=Integer.parseInt(s13);
                int i14=Integer.parseInt(s14);
                int i15=Integer.parseInt(s15);
                int i16=Integer.parseInt(s16);

                int o1=Integer.parseInt(p1);
                int o2=Integer.parseInt(p2);
                int o3=Integer.parseInt(p3);
                int o4=Integer.parseInt(p4);
                int o5=Integer.parseInt(p5);
                int o6=Integer.parseInt(p6);
                int o7=Integer.parseInt(p7);
                int o8=Integer.parseInt(p8);
                int o9=Integer.parseInt(p9);
                int o10=Integer.parseInt(p10);
                int o11=Integer.parseInt(p11);
                int o12=Integer.parseInt(p12);
                int o13=Integer.parseInt(p13);
                int o14=Integer.parseInt(p14);
                int o15=Integer.parseInt(p15);
                int o16=Integer.parseInt(p16);

                int f1=i1-o1;
                int f2=i2-o2;
                int f3=i3-o3;
                int f4=i4-o4;
                int f5=i5-o5;
                int f6=i6-o6;
                int f7=i7-o7;
                int f8=i8-o8;
                int f9=i9-o9;
                int f10=i10-o10;
                int f11=i11-o11;
                int f12=i12-o12;
                int f13=i13-o13;
                int f14=i14-o14;
                int f15=i15-o15;
                int f16=i16-o16;

                String g1=Integer.toString(f1);
                String g2=Integer.toString(f2);
                String g3=Integer.toString(f3);
                String g4=Integer.toString(f4);
                String g5=Integer.toString(f5);
                String g6=Integer.toString(f6);
                String g7=Integer.toString(f7);
                String g8=Integer.toString(f8);
                String g9=Integer.toString(f9);
                String g10=Integer.toString(f10);
                String g11=Integer.toString(f11);
                String g12=Integer.toString(f12);
                String g13=Integer.toString(f13);
                String g14=Integer.toString(f14);
                String g15=Integer.toString(f15);
                String g16=Integer.toString(f16);

                w1.setText(g1);
                w2.setText(g2);
                w3.setText(g3);
                w4.setText(g4);
                w5.setText(g5);
                w6.setText(g6);
                w7.setText(g7);
                w8.setText(g8);
                w9.setText(g9);
                w10.setText(g10);
                w11.setText(g11);
                w12.setText(g12);
                w13.setText(g13);
                w14.setText(g14);
                w15.setText(g15);
                w16.setText(g16);
            }
        });
    }
}